version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - ./faithbyte/db:/var/lib/postgresql/faithbyte  # Mount the local directory to the container
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
