version: '1.1'


volumes: 
  production_postgres_data: {}
  production_postgres_data_backups: {}
  media: {}



services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
      # command: ["gunicorn", "myproject.wsgi:application", "--bind", "0.0.0.0:8000"]
    image: faithbyte_production_django:latest
    depends_on:
      - postgres
      - redis
    volumes:
      - ./media:/app/media/
    ports:
      - "8000:5000"
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: bash /start
    environment:
      - DATABASE_URL=postgresql://debug:debug@postgres:5432/faithbyte
      - CELERY_BROKER_URL=redis://redis:6379/0
  
  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: faithbyte_production_postgres:latest
    volumes:
      - production_postgres_data:/var/lib/postgresql/data
      - production_postgres_data_backups:/backups
    env_file:
      - ./.envs/.production/.postgres
    ports:
      - "5433:5432"

  redis:
    image: redis:6

      