version: '3.8'

volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  media: {}
  static_files: {} 
  static: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: faithbyte_production_django:latest
    depends_on:
      - postgres
      - redis
    volumes:
      - ./media:/app/media
      - ./static:/app/static
      - static_files:/app/staticfiles
    ports:
      - "8000:5000"
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    environment:
      - DATABASE_URL=postgresql://debug:debug@postgres:5432/faithbyte
      - CELERY_BROKER_URL=redis://redis:6379/0
    command: ["gunicorn", "config.wsgi:application", "--bind", "0.0.0.0:8000"]

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: faithbyte_production_postgres:latest
    volumes:
      - production_postgres_data:/var/lib/postgresql/data
      - production_postgres_data_backups:/backups
    env_file:
      - ./.envs/.production/.postgres
    ports:
      - "5433:5432"

  redis:
    image: redis:6
    ports:
      - "6379:6379"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - django
    volumes:
      - ./media:/media
      - static_files:/app/staticfiles
      - ./static:/app/static
      - ./compose/production/nginx:/etc/nginx/conf.d/
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
