name: Django CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensure full history is fetched

      - name: List files to verify directory
        run: |
          echo "Current directory:"
          pwd
          echo "Listing files:"
          ls -la

      - name: Change to backend directory
        run: |
          if [ -d "faithbyte-backend" ]; then
            cd faithbyte-backend
            echo "Successfully changed directory!"
          else
            echo "Directory 'faithbyte-backend' not found."
            exit 1
          fi

      - name: Pull latest changes
        run: |
          git pull origin main

      - name: Run migrations
        run: |
          sudo -S docker-compose -f production.yml run --rm django python manage.py migrate
