name: Django CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploying
        run: |
          cd faithbyte-backend/
          git pull origin main
          echo 'Project updated'
          sudo -S docker-compose -f production.yml run --rm django python manage.py migrate
