name: Django CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: List files for debugging
        run: |
          ls -la

      - name: Change to backend directory
        run: |
          cd faithbyte-backend || { echo "Directory not found!"; exit 1; }

      - name: Pull latest changes
        run: |
          git pull origin main

      - name: Run migrations
        run: |
          sudo -S docker-compose -f production.yml run --rm django python manage.py migrate
