name: Django CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Ensure the correct version is set

      - name: Deploying
        run: |
          cd faithbyte_backend/
          git pull origin main
          echo 'project updated'
          sudo -S docker-compose -f production.yml run --rm django python manage.py migrate

    # Optional: Run tests if needed
    # - name: Run tests
    #   run: python manage.py test
